  server:
    port: 8081

  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN:6238619409:AAEzdutzOER5slDVsTbSRIZnezfU7Hqmz7U}

  admin:
    allowed_users:
      Marandyuk_Anatolii,
      HomerTheBald,
      kyomexd,
      etozhealexis,
      NikitaAkimovv

  jwt:
    secret:
      access: ${JWT_ACCESS_KEY:qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==}
      refresh: ${JWT_REFRESH_KEY:zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==}

  spring:
    datasource:
      url: jdbc:postgresql://${ORCHESTRATOR_DB_HOST:localhost}:${ORCHESTRATOR_DB_PORT:5433}/orchestrator-db
      username: ${ORCHESTRATOR_DB_USER:postgres}
      password: ${ORCHESTRATOR_DB_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

    thymeleaf:
      enabled: true
      prefix: classpath:/templates/
      suffix: .html

    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

    application:
      name: orchestrator-service

    liquibase:
      enabled: true
      change-log: /db/changelog/db.changelog-master.xml

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka

  logging:
    level:
      org.zalando.logbook: TRACE

  management:
    endpoints:
      web:
        exposure:
          include: "*"