version: '3.1'

services:
  orchestrator-db:
    container_name: orchestrator-db
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator-db
    restart: always
  recognizer-db:
    container_name: recognizer-db
    image: postgres:14.1-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recognizer-db
    restart: always
  eureka:
    container_name: eureka
    image: kyomexd/overmoney:eureka
    ports:
      - '8761:8761'
  orchestrator:
    container_name: orchestrator
    image: kyomexd/overmoney:orchestrator
    ports:
      - '8081:8081'
    depends_on:
      - orchestrator-db
  recognizer:
    container_name: recognizer
    image: kyomexd/overmoney:recognizer
    ports:
      - '8080:8080'
    depends_on:
      - recognizer-db