  name: Build & Deploy

  on:
    push:
      branches:
        - master

  jobs:
    push_compose:
      name: Push docker-compose.yaml to remote server
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Copy docker-compose.yaml via SSH
          uses: appleboy/scp-action@master
          with:
            host: overridetech.ru
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            source: "docker-compose.yaml"
            target: "/home/vasya"
            overwrite: true

    build_and_push_images:
      name: Push image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Eureka Build and Push to Dockerhub
          uses: docker/build-push-action@v2
          with:
            context: /eureka_server
            file: /eureka_server/Dockerfile
            push: true
            tags: nekromant322/overmoney:eureka

        - name: Orchestrator Build and Push to Dockerhub
          uses: docker/build-push-action@v2
          with:
            context: /orchestrator_service
            file: /orchestrator_service/Dockerfile
            push: true
            tags: nekromant322/overmoney:orchestrator

        - name: Recognizer Build and Push to Dockerhub
          uses: docker/build-push-action@v2
          with:
            context: /recognizer_service
            file: /recognizer_service/Dockerfile
            push: true
            tags: nekromant322/overmoney:recognizer

    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: [build_and_push_image]
      steps:
        - name: Connect with SSH and Deploy
          uses: appleboy/ssh-action@v0.1.8
          with:
            host: overridetech.ru
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              echo RECOGNIZER_DB_USER = ${{ secrets.RECOGNIZER_DB_USER }} > overmoney-env.txt
              echo RECOGNIZER_DB_PASSWORD = ${{ secrets.RECOGNIZER_DB_PASSWORD }} >> overmoney-env.txt
              echo ORCHESTRATOR_DB_USER = ${{ secrets.ORCHESTRATOR_DB_USER }} >> overmoney-env.txt
              echo ORCHESTRATOR_DB_PASSWORD = ${{ secrets.ORCHESTRATOR_DB_PASSWORD }} >> overmoney-env.txt
            
              sudo -S docker stop eureka
              sudo -S docker stop recognizer
              sudo -S docker stop orchestrator
              sudo -S docker rm eureka
              sudo -S docker rm recognizer
              sudo -S docker rm orchestrator
              sudo -S docker rmi nekromant322/overmoney:eureka
              sudo -S docker rmi nekromant322/overmoney:recognizer
              sudo -S docker rmi nekromant322/overmoney:orchestrator
              sudo -S docker compose --env-file overmoney-env.txt up -d eureka recognizer orchestrator
              sudo -S docker ps -a  
              rm overmoney-env.txt